{% set name = "deepgram-sdk" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deepgram-sdk-{{ version }}.tar.gz
  sha256: 80dfc88eeeba0a6b7de983d78724c3b82ffa58164e3a647e81da6546c408ad06

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.10
  run:
    - python >=3.10
    - httpx >=0.25.2,<0.26.0
    - websockets >=12.0,<13.0
    - typing-extensions >=4.9.0,<5.0.0
    - dataclasses-json >=0.6.3,<0.7.0
    # - asyncio >=3.4.3,<4.0.0  # Disabling as ayncio is in standard lib after python 3.3
    - aiohttp >=3.9.1,<4.0.0
    - verboselogs >=1.7,<2.0
    - python-dotenv

test:
  imports:
    - deepgram
  commands:
    # Disabled as it is complaining about ayncio
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/deepgram/python-sdk
  doc_url: https://developers.deepgram.com/
  summary: Python SDK for the Deepgram automated speech recognition platform.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
