{% set name = "deepgram-sdk" %}
{% set version = "3.10.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 24384e9ffea5bf1b2f8bb305c34b71beb6b8c5aca0f55d019ebc9f506af92fd0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - httpx >=0.25.2,<0.26.0
    - websockets >=12.0.0,<13.0.0
    - typing_extensions >=4.9.0,<5.0.0
    - dataclasses-json >=0.6.3,<0.7.0
    - aiohttp >=3.9.1,<4.0.0
    - aiofiles >=23.2.1,<24.0.0
    - aenum >=3.1.0,<4.0.0
    - deprecation >=2.1.0,<3.0.0

test:
  imports:
    - deepgram
  commands:
    # Disabled as it is complaining about ayncio
    # - pip check
  requires:
    - pip
    - pyaudio >=0.2.14,<0.3.0
    - python {{ python_min }}

about:
  home: https://github.com/deepgram/python-sdk
  doc_url: https://developers.deepgram.com/
  summary: Python SDK for the Deepgram automated speech recognition platform.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
