{% set name = "deepgram-sdk" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deepgram-sdk-{{ version }}.tar.gz
  sha256: d2f9cc945d8849498271a0014e33b41f593ce719cebdf01044bd69003ee40b36

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.0
  run:
    - python >=3.0
    - aiohttp
    - websockets
    - typing-extensions

test:
  imports:
    - deepgram
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepgram/python-sdk
  doc_url: https://developers.deepgram.com/
  summary: Python SDK for the Deepgram automated speech recognition platform.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
