{% set name = "deepgram-sdk" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: abc5b6c56920de5e1eaa3d9970204330ad48b4fc688e774dda78d862dd3976a8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.10,<4.0
  run:
    - python >=3.10,<4.0
    - httpx >=0.25.2,<0.26.0
    - websockets >=12.0,<13.0
    - typing-extensions >=4.9.0,<5.0.0
    - dataclasses-json >=0.6.3,<0.7.0
    - aiohttp >=3.9.1,<4.0.0
    - aiofiles >=23.2.1,<24.0.0
    - aenum >=3.1.0,<4.0.0

test:
  imports:
    - deepgram
  commands:
    # Disabled as it is complaining about ayncio
    # - pip check
  requires:
    - pip
    - pyaudio >=0.2.14,<0.3.0

about:
  home: https://github.com/deepgram/python-sdk
  doc_url: https://developers.deepgram.com/
  summary: Python SDK for the Deepgram automated speech recognition platform.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
