{% set name = "deepgram-sdk" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deepgram-sdk-{{ version }}.tar.gz
  sha256: 0653a648cbe556b4b2075c52a1adcdcd0064ba6af98e8b4812161c78442cc76f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.0
  run:
    - python >=3.0
    - aiohttp
    - websockets
    - typing-extensions

test:
  imports:
    - deepgram
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepgram/python-sdk
  doc_url: https://developers.deepgram.com/
  summary: Python SDK for the Deepgram automated speech recognition platform.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
