schema_version: 1

context:
  name: deepgram-sdk
  version: "5.0.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: d74f294373f2617de6c7dd43672e3c661b2642b3b3f45378d996c40a174af253

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - poetry-core
  run:
    - python >=${{ python_min }}
    - httpx >=0.21.2
    - pydantic >=1.9.2
    - pydantic-core >=2.18.2
    - typing_extensions >=4.0.0
    - websockets >=12.0    
tests:
  - python:
      imports:
        - deepgram
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Python SDK for the Deepgram automated speech recognition platform.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/deepgram/python-sdk
  documentation: https://developers.deepgram.com/

extra:
  recipe-maintainers:
    - thewchan
