schema_version: 1

context:
  name: deepgram-sdk
  version: "4.8.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: b5cfd16e657121f9db05d9a594c4f4dfab604bb3885d17e2ae12a7923cd11ba3

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
    - wheel
  run:
    - python >=${{ python_min }}
    - httpx >=0.25.2,<0.26.0
    - websockets >=12.0
    - typing_extensions >=4.9.0,<5.0.0
    - dataclasses-json >=0.6.3,<0.7.0
    - aiohttp >=3.9.1,<4.0.0
    - aiofiles >=23.2.1,<24.0.0
    - aenum >=3.1.0,<4.0.0
    - deprecation >=2.1.0,<3.0.0

tests:
  - python:
      imports:
        - deepgram
      # No Pip check due to asyncio
      pip_check: false
      python_version: ${{ python_min }}.*

about:
  summary: Python SDK for the Deepgram automated speech recognition platform.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/deepgram/python-sdk
  documentation: https://developers.deepgram.com/

extra:
  recipe-maintainers:
    - thewchan
